In [33]:
import numpy as np
def split(word):
    return [char for char in word]

def alignStrings(x, y, c_insert, c_delete, c_sub):
    #array prints flipped
    
    #x and y are 2 strings, need to split the strings into symbols
    X = split(x)
    Y = split(y)
    
    #n_x and n_y are how many symbols are in X and Y
    n_x = len(X)
    n_y = len(Y)
    
    #if x[i] = y[i], then NO OP
    
    #S = cost matrix
    #initalize s, will need to return S
    S = [[0 for yIndex in range(n_y + 1)] for xIndex in range(n_x + 1)] #S should be of size [n_x][n_y]
    S[0][0] = 0 
    
    for xIndex in range(n_x + 1):
        S[xIndex][0] = xIndex*c_insert
    for yIndex in range(n_y + 1):
        S[0][yIndex] = yIndex*c_delete
    
    x_index = 1
    while x_index < n_x + 1:
        y_index = 1
        while y_index < n_y + 1:
            if(X[x_index-1] == Y[y_index-1]):
                S[x_index][y_index] = S[x_index-1][y_index-1]
                
            else:
                S[x_index][y_index] = min((S[x_index-1][y_index-1] + c_sub, S[x_index][y_index-1] + c_delete, S[x_index-1][y_index] + c_insert))
            y_index+=1
        x_index+=1
    
    return S

x = "EXPONENTIAL"
y = "POLYNOMIAL"
cInsert = 2
cDelete = 1
cSub = 2

S = alignStrings(x, y, cInsert, cDelete, cSub)
print("Cost Matrix S:")
print(np.matrix(S))

Cost Matrix S:
[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 2  2  3  4  5  6  7  8  9 10 11]
 [ 4  4  4  5  6  7  8  9 10 11 12]
 [ 6  4  5  6  7  8  9 10 11 12 13]
 [ 8  6  4  5  6  7  8  9 10 11 12]
 [10  8  6  6  7  6  7  8  9 10 11]
 [12 10  8  8  8  8  8  9 10 11 12]
 [14 12 10 10 10  8  9 10 11 12 13]
 [16 14 12 12 12 10 10 11 12 13 14]
 [18 16 14 14 14 12 12 12 11 12 13]
 [20 18 16 16 16 14 14 14 13 11 12]
 [22 20 18 16 17 16 16 16 15 13 11]]


In [34]:
def extractAlignment(S, x, y, c_insert, c_delete, c_sub):
    n_x = len(x)
    n_y = len(y)
    
    #start at very end of S[n_x][n_y]
    xIndex = n_x
    yIndex = n_y
    
    #have an array to store operations
    a = []
    
    while xIndex != 0 and yIndex != 0:
        
        if (S[xIndex][yIndex] == S[xIndex - 1][yIndex - 1] and x[xIndex - 1] == y[yIndex - 1]):
            a.append(["no-op", xIndex])
            xIndex -= 1
            yIndex -= 1
                        
        elif S[xIndex][yIndex] == S[xIndex-1][yIndex-1] + c_sub:
            a.append(["sub", xIndex])
            xIndex -= 1
            yIndex -= 1
                            
        elif S[xIndex][yIndex] == S[xIndex - 1][yIndex] + c_insert:
            a.append(["insert", xIndex])
            xIndex -= 1
                            
        elif S[xIndex][yIndex] == S[xIndex][yIndex - 1] + c_delete:
            a.append(["delete", xIndex])
            yIndex -= 1
            
#         print(xIndex, yIndex)
    #if xIndex != 0, then append amount of deletes that xIndex is at
    #if xIndex = 2, then append 2 deletes
    while xIndex != 0:
        a.append(["delete", xIndex])
        xIndex -= 1
        
    #if yIndex != 0, then append amount of insert that yIndex is at
    #if yIndex = 1, then append 2 insert
    while yIndex != 0:
        a.append(["insert", xIndex])
        yIndex -= 1

    return a[::-1]

print("Ops:")
a = extractAlignment(S, x, y, cInsert, cDelete, cSub)
print(a)


Ops:
[['delete', 1], ['delete', 2], ['no-op', 3], ['no-op', 4], ['sub', 5], ['sub', 6], ['no-op', 7], ['delete', 7], ['sub', 8], ['no-op', 9], ['no-op', 10], ['no-op', 11]]


In [36]:
def ExtractOp(lst):
    return [item[0] for item in lst]
def ExtractIndex(lst):
    return [item[1] for item in lst]

def commonSubstrings(x, L, a):
    
    X = split(x)
    #list of characters
    curr = ''
    #list of subStrings 
    subStrings = []
    
    #extract operations and the x[index] into 2 seperate arrays
    Ops = ExtractOp(a)
    xIndex = ExtractIndex(a)
    
    pos = 0
    
    #iterate through Ops looking for position where it's no-op
    for pos in range(len(Ops)):
        if Ops[pos] == "no-op":
            #get the xIndex at this position
            xPos = xIndex[pos] - 1
            #get the letter of x at xPos
            curr += X[xPos]
        else:     
            if len(curr) >= L:
                subStrings.append(curr)
#                 print(len(curr), curr)
            curr = ''
    
    #check if curr >= L
    if len(curr) >= L:
        subStrings.append(curr)
    
    return subStrings

L = 1
print("Sub-Strings:")
SubString = commonSubstrings(x, L, a)
print(SubString)

Sub-Strings:
['PO', 'N', 'IAL']


In [32]:
f = open("Song1_Folsom_Prison.txt", "r")
if f.mode == 'r':
    x = f.read()

g = open("Song2_Crescent_City_Blues.txt", "r")
if g.mode == 'r':
    y = g.read()

cInsert = 1
cDelete = 1
cSub = 1
#call alignStrings
S = alignStrings(x, y, cInsert, cDelete, cSub)

#call extractAlignment
a = extractAlignment(S, x, y, cInsert, cDelete, cSub)

#call commonSubstrings
L = 10
commonSubstrings(x, L, a)

18 I hear the train a
12  it's rollin
28 round the bend  And I ain't 
26  since I don't know when  
42     When I was just a baby my mama told me
34   When I hear that whistle blowin'
19  I hang my head and
22  rich folks eatin' in 
36  fancy dining car  They're probably 
44  if that railroad train was mine  I bet I'd 
43 n a little farther down the line  Far from 
